apiVersion: apps/v1
kind: Deployment
metadata:
  name: nina-app-v2
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nina-app
  template:
    metadata:
      labels:
        name: nina-app
    spec:
      containers:
      - name: nina-app
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
